#!/bin/bash

#--------------------------------------------------------------------------------------------------------------------------------
#                                             Trabalho 1
#                             Taxas de Leitura/Escrita de processos em bash
#
# Guião
#    O objetivo do trabalho é o desenvolvimento de um script em bash para obter estatísticas sobre
#    as leituras e escritas que os processos estão a efetuar. Esta ferramenta permite visualizar o número total
#    de bytes de I/O que um processo leu/escreveu e também a taxa de leitura/escrita correspondente aos
#    últimos s segundos para uma seleção de processos (o valor de s é passado como parâmetro).
#
# Liliana Ribeiro 108713
# Gonçalo Sousa 108133
#--------------------------------------------------------------------------------------------------------------------------------

# Inicialização de Arrays

#-----------Defenir variaveis de default-------------
datemin=0
datemax=$(date +"%s") #data atual em segundos
gamPidMin=0
regexString='^[0-9]+$'
regexDate='^((Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec)) +(0?[1-9]|[12][0-9]|3[01]) +([01]?[0-9]|2[0-3]):[0-5][0-9]'

#----------menu---------------
function menu() { # Menu de execução do programa.
    echo "------------------------  Menu de Execução do Programa  ------------------------"
    echo
    echo "        ~~~~~~~~~~~~~~~~  Filtros  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~        "
    echo " -c  -----> Seleção  dos  processos  a  visualizar  pode  ser  realizada através de uma expressão regular."
    echo " -s  -----> Seleção de processos a visualizar num periodo temporal - data mínima"
    echo " -e  -----> Seleção de processos a visualizar num periodo temporal - data máxima"
    echo " -u  -----> Seleção de processos a visualizar através do nome do utilizador"
    echo " -m  -----> Seleção de processos a visualizar através de uma gama de pids - minimo"
    echo " -M  -----> Seleção de processos a visualizar através de uma gama de pids - máximo"
    echo " -p  -----> Número de processos a visualizar"
    echo
    echo "        ~~~~~~~~~~~~~~~~  Ordenação (Escolher apenas uma)  ~~~~~~~~~~~~~        "
    echo " -r  -----> Ordenação reversa"
    echo " -w  -----> Ordenação da tabela por valores de escrita"
    echo
    echo " NOTA: o último argumento terá de ser o número de segundos pertendido"

}

#----------guardar e validar opcoes--------------
while getopts "c:s:e:u:m:M:rw" option; do

    #confere se o argumento passado não é uma suposta opção
    if [[ ${OPTARG:0:1} == - ]]; then
        echo "ERRO --> A opcao -$option requer um argumento"
        echo
        menu
        exit 1
    fi

    #Adiciona os value passados ao array argOpc com key option, caso nada seja passado adiciona o value "empty"
    if [[ -z "$OPTARG" ]]; then
        arrayOpc[$option]=empty
    else
        arrayOpc[$option]=${OPTARG}
    fi

    #----Tratamento de opcoes---

    case $option in
    c)
        #verifica se é uma string
        if ! [[ $OPTARG =~ $regexString ]]; then
            echo "ERRO --> Insira uma expressão válida" >&2
            echo
            menu
            exit 1
        fi

        #Guarda a expressão regular
        expReg=$OPTARG
        ;;

    s)
        #verifica se é uma data
        if ! [[ $OPTARG =~ $regexDate ]]; then
            echo "ERRO --> Insira uma data válida" >&2
            echo
            menu
            exit 1
        fi

        #Guarda a data minima
        dateMin=$OPTARG
        ;;

    e)
        #Guarda a data maxima
        dateMax = $OPTARG
        #verifica se é uma data
        if [[ ! "$str" =~ $regexString ]]; then
            echo "Insira uma data válida" >&2
            echo
            opcoes
            exit 1
        fi
        ;;

    u) ;;

    m) ;;

    M) ;;

    p) ;;

    r) ;;

    w) ;;

    \
        *) #Passagem de argumentos inválidos
        menu
        exit 1
        ;;
    esac
done

# ---------------- Validação dos argumetos passados --------------------

# Verifica se o ultimo argumento é um número
if ! [[ ${@: -1} =~ $regexString ]]; then
    echo "Insira como último argumento o número de segundos que pertende"
    menu
    exit 1
fi
